const WALLET = 'WALLET';
const WALLET_PUBLIC_KEY = 'WALLET_PUBLIC_KEY';
const WALLET_SESSION_ID = 'WALLET_SESSION_ID';

const SOUND_ENABLE_GLOBAL = 'SOUND_ENABLE_GLOBAL';

export default {
  WALLET,
  WALLET_PUBLIC_KEY,
  WALLET_SESSION_ID,

  SOUND_ENABLE_GLOBAL,
};
